import { chromium, expect, type BrowserContext } from "@playwright/test";
import { randomBytes } from "node:crypto";
import { hash } from "bcryptjs";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { db } from "../src/lib/db";
import { dateLabel } from "../src/lib/domain";
import { demoFloorTables } from "../src/lib/floor-layout";

async function main() {
  const origin = process.env.APP_ORIGIN || "http://localhost:3000";
  const database = new URL(process.env.DATABASE_URL || "");
  if (!["localhost", "127.0.0.1"].includes(new URL(origin).hostname) || !["localhost", "127.0.0.1"].includes(database.hostname) || database.pathname !== "/gali_blue" || process.env.NODE_ENV === "production") throw new Error("Test reserve a la base locale gali_blue.");
  const original = await db.settings.findUniqueOrThrow({ where: { id: 1 } });
  const marker = randomBytes(4).toString("hex");
  const actor = `Floor ${marker}`;
  const email = `floor-${marker}@example.test`;
  const password = randomBytes(24).toString("base64url");
  const date = dateLabel(new Date(Date.now() + 86400000), "yyyy-MM-dd");
  const time = (original.serviceTimes as string[])[0];
  const phone = `+2126${parseInt(marker, 16).toString().slice(0, 8).padStart(8, "0")}`;
  const artifacts = fileURLToPath(new URL("../storage/checks", import.meta.url));
  await mkdir(artifacts, { recursive: true });
  const browser = await chromium.launch({ channel: "msedge", headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage();
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  let tableId = "";
  let staffId = "";
  let reservationId = "";
  let vipTableId = "";
  const clients: BrowserContext[] = [];
  try {
    staffId = (await db.staff.create({ data: { name: actor, email, job: "Test temporaire", role: "ADMIN", passwordHash: await hash(password, 12) } })).id;
    const table = await db.diningTable.create({ data: { name: `PX-${marker.slice(0, 4)}`, area: "Salle test", seats: 4, planX: 65, planY: 80 } });
    tableId = table.id;
    const vipTable = await db.diningTable.create({ data: { name: `VP-${marker.slice(0, 4)}`, area: "VIP test", seats: 8, vip: true, planX: 65, planY: 87 } });
    vipTableId = vipTable.id;
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: true, floorBookingEnabled: false, closedDates: (original.closedDates as string[]).filter(value => value !== date) } });
    await page.goto(`${origin}/connexion`, { waitUntil: "networkidle" });
    await page.getByLabel("Email professionnel").fill(email);
    await page.locator('input[name="password"]').fill(password);
    await page.getByRole("button", { name: "Se connecter", exact: true }).click();
    await expect(page).toHaveURL(/dashboard/);
    await page.goto(`${origin}/dashboard?view=settings`, { waitUntil: "networkidle" });
    await page.getByRole("switch", { name: "Reservation sur plan 2D", exact: true }).check();
    await page.getByLabel("Image du plan de salle", { exact: true }).selectOption("/images/floor-plan-demo.jpg");
    const saved = page.waitForResponse(response => response.url().endsWith("/api/admin") && response.request().method() === "POST");
    await page.getByRole("button", { name: "Enregistrer", exact: true }).click();
    expect((await saved).status()).toBe(200);
    const settings = await db.settings.findUniqueOrThrow({ where: { id: 1 } });
    expect(settings.floorBookingEnabled).toBe(true);
    const headers = { Origin: origin };
    const invalid = await page.request.post(`${origin}/api/admin`, { headers, data: { resource: "settings", data: { ...settings, classicBookingEnabled: false, floorBookingEnabled: false } } });
    expect(invalid.status()).toBe(400);
    await page.goto(`${origin}/dashboard?view=tables`, { waitUntil: "networkidle" });
    await page.getByRole("button", { name: `Modifier ${table.name}`, exact: true }).click();
    await page.getByRole("button", { name: "Positionner la table sur le plan" }).click({ position: { x: 140, y: 100 } });
    const positionSave = page.waitForResponse(response => response.url().endsWith("/api/admin") && response.request().method() === "POST");
    await page.getByRole("dialog").getByRole("button", { name: "Enregistrer", exact: true }).click();
    expect((await positionSave).status()).toBe(200);
    await expect(page.getByRole("dialog")).toHaveCount(0);
    const positioned = await db.diningTable.findUniqueOrThrow({ where: { id: tableId } });
    expect(positioned.planX).not.toBe(65);
    await db.diningTable.update({ where: { id: tableId }, data: { planX: 65, planY: 80 } });
    await page.goto(`${origin}/salle`, { waitUntil: "networkidle" });
    await page.getByLabel("Service", { exact: true }).selectOption(time);
    await expect(page.locator(".plan-table")).toHaveCount(demoFloorTables.length + 2);
    for (const item of demoFloorTables) await expect(page.locator(".plan-table strong").filter({ hasText: new RegExp(`^${item.name}$`) })).toHaveCount(1);
    await page.getByRole("radio", { name: "VIP", exact: true }).check();
    await expect(page.locator(".plan-table")).toHaveCount(10);
    await page.getByRole("radio", { name: "Toutes", exact: true }).check();
    for (const [width, height] of [[1440, 1100], [1024, 1000], [768, 1000], [390, 844], [320, 740]]) {
      await page.setViewportSize({ width, height });
      await expect(page.locator(".plan-loading")).toHaveCount(0);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
      expect(await page.locator(".plan-canvas img").evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
      await page.locator(".plan-table-list").getByRole("button", { name: `${table.name}, 4 places, Disponible`, exact: true }).click();
      await expect(page.getByRole("dialog")).toBeVisible();
      await expect(page.getByRole("link", { name: "Reserver cette table" })).toBeVisible();
      if (width === 390) await page.screenshot({ path: `${artifacts}/floor-popup-mobile.png` });
      await page.keyboard.press("Escape");
      await expect(page.getByRole("dialog")).not.toBeVisible();
    }
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.screenshot({ path: `${artifacts}/floor-desktop.png`, fullPage: true });
    await page.locator(".plan-table").filter({ hasText: table.name }).click();
    await page.getByRole("link", { name: "Reserver cette table" }).click();
    await expect(page).toHaveURL(new RegExp(`/reserver\\?table=${tableId}`));
    await expect(page.locator(".booking-table-selection")).toContainText(table.name);
    await expect(page.getByRole("button", { name: time, exact: true })).toHaveAttribute("aria-pressed", "true");
    await page.getByRole("button", { name: "Continuer", exact: true }).click();
    await page.getByLabel("Nom complet").fill(actor);
    await page.getByLabel("Telephone", { exact: true }).fill(phone);
    await page.locator('input[name="consent"]').check();
    await page.getByRole("button", { name: "Envoyer ma demande", exact: true }).click();
    await expect(page.locator(".booking-success")).toBeVisible();
    const reservation = await db.reservation.findFirstOrThrow({ where: { name: actor } });
    reservationId = reservation.id;
    expect(reservation.requestedTableId).toBe(tableId);
    expect(reservation.status).toBe("CALL_PENDING");
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`${origin}/dashboard?view=reservations`, { waitUntil: "networkidle" });
    await page.getByRole("button", { name: `Ouvrir la reservation de ${actor}`, exact: true }).click();
    await page.getByRole("button", { name: "Sans reponse, rappeler", exact: true }).click();
    await expect(page.locator(".detail-title .badge")).toHaveText("A rappeler");
    await expect(page.locator(".call-summary")).toContainText("1 tentative(s)");
    await page.getByRole("dialog").screenshot({ path: `${artifacts}/call-mobile.png` });
    expect(await page.getByRole("dialog").evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
    await page.getByRole("button", { name: "Confirmer par telephone", exact: true }).click();
    await expect(page.locator(".detail-title .badge")).toHaveText("Confirmee par appel");
    await expect(page.locator(".table-checkboxes input:checked")).toHaveCount(1);
    await page.keyboard.press("Escape");
    for (const [index, width] of [390, 320].entries()) {
      const clientContext = await browser.newContext({ viewport: { width, height: 844 }, isMobile: true, hasTouch: true });
      clients.push(clientContext);
      const client = await clientContext.newPage();
      const name = `${actor} VIP ${index + 1}`;
      if (index === 0) {
        await client.goto(`${origin}/reserver`, { waitUntil: "networkidle" });
        await client.getByRole("radio", { name: "VIP", exact: true }).tap();
        await expect(client.locator(".loading-inline")).toHaveCount(0);
        await client.getByRole("button", { name: time, exact: true }).tap();
        await client.screenshot({ path: `${artifacts}/classic-vip-mobile.png`, fullPage: true });
      } else {
        await client.goto(`${origin}/salle`, { waitUntil: "networkidle" });
        await client.getByLabel("Service", { exact: true }).selectOption(time);
        await client.getByRole("radio", { name: "VIP", exact: true }).tap();
        await client.locator(".plan-table-list").getByRole("button", { name: `${vipTable.name}, 8 places, Disponible, VIP`, exact: true }).tap();
        await expect(client.getByRole("dialog")).toContainText("VIP");
        await client.screenshot({ path: `${artifacts}/vip-popup-mobile.png` });
        await client.getByRole("link", { name: "Reserver cette table" }).tap();
        await expect(client.locator(".booking-category")).toContainText("VIP");
      }
      expect(await client.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
      await client.getByRole("button", { name: "Continuer", exact: true }).tap();
      await client.getByLabel("Nom complet").fill(name);
      await client.getByLabel("Telephone", { exact: true }).fill(phone);
      await client.locator('input[name="consent"]').check();
      await client.getByRole("button", { name: "Envoyer ma demande", exact: true }).tap();
      await expect(client.locator(".booking-success")).toBeVisible();
      const savedClient = await db.reservation.findFirstOrThrow({ where: { name } });
      expect(savedClient.vip).toBe(true);
      expect(savedClient.status).toBe("CALL_PENDING");
      if (index === 1) expect(savedClient.requestedTableId).toBe(vipTableId);
    }
    await page.goto(`${origin}/salle?occupied=1`, { waitUntil: "networkidle" });
    await page.getByLabel("Service", { exact: true }).selectOption(time);
    await page.locator(".plan-table-list").getByRole("button", { name: `${table.name}, 4 places, Pas disponible`, exact: true }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toHaveText("Pas disponible");
    await expect(page.getByRole("dialog").getByRole("link", { name: "Reserver cette table" })).toHaveCount(0);
    await page.keyboard.press("Escape");
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: false } });
    await page.goto(`${origin}/reserver?floorOnly=1`, { waitUntil: "networkidle" });
    await expect(page).toHaveURL(/\/salle$/);
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: true, floorBookingEnabled: false } });
    const disabled = await page.request.get(`${origin}/api/availability?floor=1&date=${date}&guests=2`);
    expect(disabled.status()).toBe(409);
    await page.goto(`${origin}/salle?disabled=1`, { waitUntil: "networkidle" });
    await expect(page).toHaveURL(/\/reserver$/);
    expect(errors).toEqual([]);
    await writeFile(`${artifacts}/floor-use-cases.json`, JSON.stringify({ success: true, generatedAt: new Date().toISOString(), canonicalTables: 38, vipTables: 9, viewports: [1440, 1024, 768, 390, 320], touchClients: 2, checks: ["Activation et placement", "38 tables et 9 VIP", "Popup et formulaire", "Rappel et confirmation mobile", "Deux clients VIP anonymes tactiles", "Table occupee", "Parcours desactives"] }, null, 2));
    console.log("PASS: 38 tables / 9 VIP, five viewports, two anonymous touch clients, call follow-up/confirmation, unavailable table and mode gates.");
  } finally {
    if (reservationId) { await db.audit.deleteMany({ where: { reservationId } }); await db.reservation.delete({ where: { id: reservationId } }); }
    const remaining = await db.reservation.findMany({ where: { name: { startsWith: actor } }, select: { id: true } });
    await db.audit.deleteMany({ where: { reservationId: { in: remaining.map(item => item.id) } } });
    await db.reservation.deleteMany({ where: { name: { startsWith: actor } } });
    await db.diningTable.deleteMany({ where: { id: { in: [tableId, vipTableId].filter(Boolean) } } });
    if (staffId) await db.staff.delete({ where: { id: staffId } });
    await db.audit.deleteMany({ where: { actor } });
    await db.rateLimit.deleteMany({ where: { key: `booking:${phone.replace(/\D/g, "")}` } });
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: original.classicBookingEnabled, floorBookingEnabled: original.floorBookingEnabled, floorPlanImage: original.floorPlanImage, closedDates: original.closedDates as string[] } });
    for (const client of clients) await client.close();
    await context.close(); await browser.close(); await db.$disconnect();
  }
}
main().catch(error => { console.error(error); process.exitCode = 1; });