import { chromium, expect } from "@playwright/test";
import { randomBytes } from "node:crypto";
import { hash } from "bcryptjs";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { db } from "../src/lib/db";
import { dateLabel } from "../src/lib/domain";
import { updateBooking } from "../src/lib/booking";

async function main() {
  const origin = process.env.APP_ORIGIN || "http://localhost:3000";
  const database = new URL(process.env.DATABASE_URL || "");
  if (!["localhost", "127.0.0.1"].includes(new URL(origin).hostname) || !["localhost", "127.0.0.1"].includes(database.hostname) || database.pathname !== "/gali_blue" || process.env.NODE_ENV === "production") throw new Error("Test reserve a la base locale gali_blue.");
  const original = await db.settings.findUniqueOrThrow({ where: { id: 1 } });
  const marker = randomBytes(4).toString("hex");
  const actor = `Floor ${marker}`;
  const email = `floor-${marker}@example.test`;
  const password = randomBytes(24).toString("base64url");
  const date = dateLabel(new Date(Date.now() + 86400000), "yyyy-MM-dd");
  const time = (original.serviceTimes as string[])[0];
  const phone = `+2126${parseInt(marker, 16).toString().slice(0, 8).padStart(8, "0")}`;
  const artifacts = fileURLToPath(new URL("../storage/checks", import.meta.url));
  await mkdir(artifacts, { recursive: true });
  const browser = await chromium.launch({ channel: "msedge", headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage();
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  let tableId = "";
  let staffId = "";
  let reservationId = "";
  try {
    staffId = (await db.staff.create({ data: { name: actor, email, job: "Test temporaire", role: "ADMIN", passwordHash: await hash(password, 12) } })).id;
    const table = await db.diningTable.create({ data: { name: `PX-${marker.slice(0, 4)}`, area: "Salle test", seats: 4, planX: 65, planY: 80 } });
    tableId = table.id;
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: true, floorBookingEnabled: false, closedDates: (original.closedDates as string[]).filter(value => value !== date) } });
    await page.goto(`${origin}/connexion`, { waitUntil: "networkidle" });
    await page.getByLabel("Email professionnel").fill(email);
    await page.locator('input[name="password"]').fill(password);
    await page.getByRole("button", { name: "Se connecter", exact: true }).click();
    await expect(page).toHaveURL(/dashboard/);
    await page.goto(`${origin}/dashboard?view=settings`, { waitUntil: "networkidle" });
    await page.getByRole("switch", { name: "Reservation sur plan 2D", exact: true }).check();
    await page.getByLabel("Image du plan de salle", { exact: true }).selectOption("/images/floor-plan-demo.jpg");
    const saved = page.waitForResponse(response => response.url().endsWith("/api/admin") && response.request().method() === "POST");
    await page.getByRole("button", { name: "Enregistrer", exact: true }).click();
    expect((await saved).status()).toBe(200);
    const settings = await db.settings.findUniqueOrThrow({ where: { id: 1 } });
    expect(settings.floorBookingEnabled).toBe(true);
    const headers = { Origin: origin };
    const invalid = await page.request.post(`${origin}/api/admin`, { headers, data: { resource: "settings", data: { ...settings, classicBookingEnabled: false, floorBookingEnabled: false } } });
    expect(invalid.status()).toBe(400);
    await page.goto(`${origin}/dashboard?view=tables`, { waitUntil: "networkidle" });
    await page.getByRole("button", { name: `Modifier ${table.name}`, exact: true }).click();
    await page.getByRole("button", { name: "Positionner la table sur le plan" }).click({ position: { x: 140, y: 100 } });
    const positionSave = page.waitForResponse(response => response.url().endsWith("/api/admin") && response.request().method() === "POST");
    await page.getByRole("dialog").getByRole("button", { name: "Enregistrer", exact: true }).click();
    expect((await positionSave).status()).toBe(200);
    await expect(page.getByRole("dialog")).toHaveCount(0);
    const positioned = await db.diningTable.findUniqueOrThrow({ where: { id: tableId } });
    expect(positioned.planX).not.toBe(65);
    await db.diningTable.update({ where: { id: tableId }, data: { planX: 65, planY: 80 } });
    await page.goto(`${origin}/salle`, { waitUntil: "networkidle" });
    await page.getByLabel("Service", { exact: true }).selectOption(time);
    for (const [width, height] of [[1440, 1100], [1024, 1000], [768, 1000], [390, 844], [320, 740]]) {
      await page.setViewportSize({ width, height });
      await expect(page.locator(".plan-loading")).toHaveCount(0);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
      expect(await page.locator(".plan-canvas img").evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
      await page.locator(".plan-table-list").getByRole("button", { name: `${table.name}, 4 places, Disponible`, exact: true }).click();
      await expect(page.getByRole("dialog")).toBeVisible();
      await expect(page.getByRole("link", { name: "Reserver cette table" })).toBeVisible();
      if (width === 390) await page.screenshot({ path: `${artifacts}/floor-popup-mobile.png` });
      await page.keyboard.press("Escape");
      await expect(page.getByRole("dialog")).not.toBeVisible();
    }
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.screenshot({ path: `${artifacts}/floor-desktop.png`, fullPage: true });
    await page.locator(".plan-table").filter({ hasText: table.name }).click();
    await page.getByRole("link", { name: "Reserver cette table" }).click();
    await expect(page).toHaveURL(new RegExp(`/reserver\\?table=${tableId}`));
    await expect(page.locator(".booking-table-selection")).toContainText(table.name);
    await expect(page.getByRole("button", { name: time, exact: true })).toHaveAttribute("aria-pressed", "true");
    await page.getByRole("button", { name: "Continuer", exact: true }).click();
    await page.getByLabel("Nom complet").fill(actor);
    await page.getByLabel("Telephone", { exact: true }).fill(phone);
    await page.locator('input[name="consent"]').check();
    await page.getByRole("button", { name: "Envoyer ma demande", exact: true }).click();
    await expect(page.locator(".booking-success")).toBeVisible();
    const reservation = await db.reservation.findFirstOrThrow({ where: { name: actor } });
    reservationId = reservation.id;
    expect(reservation.requestedTableId).toBe(tableId);
    expect(reservation.status).toBe("CALL_PENDING");
    await updateBooking({ id: reservation.id, action: "transition", status: "PROVISIONAL" }, { id: staffId, name: actor, role: "ADMIN" });
    await page.goto(`${origin}/salle?occupied=1`, { waitUntil: "networkidle" });
    await page.getByLabel("Service", { exact: true }).selectOption(time);
    await page.locator(".plan-table-list").getByRole("button", { name: `${table.name}, 4 places, Pas disponible`, exact: true }).click();
    await expect(page.getByRole("dialog").getByRole("status")).toHaveText("Pas disponible");
    await expect(page.getByRole("dialog").getByRole("link", { name: "Reserver cette table" })).toHaveCount(0);
    await page.keyboard.press("Escape");
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: false } });
    await page.goto(`${origin}/reserver?floorOnly=1`, { waitUntil: "networkidle" });
    await expect(page).toHaveURL(/\/salle$/);
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: true, floorBookingEnabled: false } });
    const disabled = await page.request.get(`${origin}/api/availability?floor=1&date=${date}&guests=2`);
    expect(disabled.status()).toBe(409);
    await page.goto(`${origin}/salle?disabled=1`, { waitUntil: "networkidle" });
    await expect(page).toHaveURL(/\/reserver$/);
    expect(errors).toEqual([]);
    console.log("PASS: dashboard activation/placement, five viewports, popup, prefilled submission, unavailable table and mode gates.");
  } finally {
    if (reservationId) { await db.audit.deleteMany({ where: { reservationId } }); await db.reservation.delete({ where: { id: reservationId } }); }
    const remaining = await db.reservation.findMany({ where: { name: actor }, select: { id: true } });
    await db.audit.deleteMany({ where: { reservationId: { in: remaining.map(item => item.id) } } });
    await db.reservation.deleteMany({ where: { name: actor } });
    if (tableId) await db.diningTable.delete({ where: { id: tableId } });
    if (staffId) await db.staff.delete({ where: { id: staffId } });
    await db.audit.deleteMany({ where: { actor } });
    await db.rateLimit.deleteMany({ where: { key: `booking:${phone.replace(/\D/g, "")}` } });
    await db.settings.update({ where: { id: 1 }, data: { classicBookingEnabled: original.classicBookingEnabled, floorBookingEnabled: original.floorBookingEnabled, floorPlanImage: original.floorPlanImage, closedDates: original.closedDates as string[] } });
    await context.close(); await browser.close(); await db.$disconnect();
  }
}
main().catch(error => { console.error(error); process.exitCode = 1; });