import { chromium, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { hash } from "bcryptjs";
import { createHash, randomBytes, randomInt } from "node:crypto";
import { mkdir, readFile, unlink } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

async function main() {
const db = new PrismaClient();
const origin = process.env.APP_ORIGIN || "http://localhost:3000";
const marker = randomBytes(5).toString("hex");
const email = `ui-${marker}@example.test`;
const customer = `TEST UI ${marker}`;
const phone = `+2126${randomInt(10000000, 100000000)}`;
const password = randomBytes(24).toString("base64url");
const browser = await chromium.launch({ channel: "msedge", headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors: string[] = [];
page.on("pageerror", error => errors.push(error.message));
const artifacts = fileURLToPath(new URL("../storage/checks", import.meta.url));
await mkdir(artifacts, { recursive: true });
const originalSettings = await db.settings.findUniqueOrThrow({ where: { id: 1 } });
let accountId = "";
let uploadedMediaId = "";
let uploadedFileName = "";
let editorId = "";
try {
  await page.goto(origin, { waitUntil: "networkidle" });
  await expect(page.locator(".entry-dialog")).toBeHidden({ timeout: 7000 });
  await expect(page.getByRole("heading", { name: "GALI BLUE", exact: true })).toBeVisible();
  await expect(page.locator(".hero-photo")).toHaveJSProperty("complete", true);
  await page.screenshot({ path: path.join(artifacts, "desktop-home.png") });
  await page.locator("#carte").scrollIntoViewIfNeeded();
  await expect(page.locator(".dish").first()).toBeVisible();
  await page.locator("#instants").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: "Ouvrir La salle", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button", { name: "Image suivante" }).click();
  await page.getByRole("button", { name: "Fermer la galerie" }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(origin, { waitUntil: "networkidle" });
  await expect(page.locator(".entry-dialog")).toBeHidden({ timeout: 7000 });
  await page.screenshot({ path: path.join(artifacts, "mobile-home.png") });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Ouvrir le menu" }).click();
  await expect(page.getByRole("navigation", { name: "Navigation principale" })).toBeVisible();
  await page.getByRole("button", { name: "Fermer le menu" }).click();
  await page.goto(`${origin}/la-carte`, { waitUntil: "networkidle" });
  await page.getByRole("tab", { name: "Au bar", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Blue signature" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Burrata & tomates de saison" })).toHaveCount(0);
  await page.goto(`${origin}/reserver`, { waitUntil: "networkidle" });
  await page.locator(".slots button:not([disabled])").first().click();
  await page.getByRole("button", { name: "Continuer" }).click();
  await page.getByLabel("Nom complet").fill(customer);
  await page.getByLabel("Telephone", { exact: true }).fill(phone);
  await page.locator('input[name="consent"]').check();
  await page.screenshot({ path: path.join(artifacts, "mobile-reservation.png") });
  await page.getByRole("button", { name: "Envoyer ma demande" }).click();
  await expect(page.getByRole("heading", { name: "A tres bientot." })).toBeVisible();
  const reservation = await db.reservation.findFirstOrThrow({ where: { name: customer } });
  expect(reservation.status).toBe("CALL_PENDING");
  expect(reservation.discountPercent).toBe(0);
  await page.goto(`${origin}/dashboard`);
  await expect(page).toHaveURL(/connexion/);
  const account = await db.staff.create({ data: { name: `UI Admin ${marker}`, email, job: "Test temporaire", role: "ADMIN", passwordHash: await hash(password, 12) } });
  accountId = account.id;
  await page.reload({ waitUntil: "networkidle" });
  await page.getByLabel("Email professionnel").fill(email);
  await page.locator('input[name="password"]').fill(password);
  await page.getByRole("button", { name: "Se connecter", exact: true }).click();
  await expect(page).toHaveURL(/dashboard/);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: path.join(artifacts, "desktop-dashboard.png") });
  await page.getByRole("link", { name: /^Reservations/ }).click();
  await page.getByLabel("Rechercher une reservation").fill(marker);
  await page.getByRole("button", { name: `Ouvrir la reservation de ${customer}` }).click();
  await page.getByRole("button", { name: "Valider apres l'appel" }).click();
  await expect(page.getByRole("dialog").locator(".detail-title")).toContainText("Provisoire");
  await page.getByRole("button", { name: "Fermer", exact: true }).click();
  await page.getByRole("link", { name: "Salle & tables" }).click();
  await expect(page.locator(".floor-table")).toHaveCount(8);
  await page.getByRole("link", { name: "Parametres", exact: true }).click();
  await expect(page.getByRole("switch", { name: /Paiement en ligne via CMI/ })).toBeDisabled();
  const imageBytes = await readFile(fileURLToPath(new URL("../public/images/interior.jpg", import.meta.url)));
  const uploadResponse = await context.request.post(`${origin}/api/media`, { headers: { origin }, multipart: { file: { name: `test-${marker}.jpg`, mimeType: "image/jpeg", buffer: imageBytes } } });
  expect(uploadResponse.status()).toBe(201);
  const uploaded = await uploadResponse.json();
  uploadedMediaId = uploaded.id;
  uploadedFileName = uploaded.url.split("/").pop();
  const mediaResponse = await context.request.get(`${origin}${uploaded.url}`);
  expect(mediaResponse.status()).toBe(200);
  expect((await mediaResponse.body()).length).toBe(imageBytes.length);
  const invalidUpload = await context.request.post(`${origin}/api/media`, { headers: { origin }, multipart: { file: { name: "invalid.svg", mimeType: "image/svg+xml", buffer: Buffer.from("<svg></svg>") } } });
  expect(invalidUpload.status()).toBe(400);
  await page.getByLabel("Reduction (%)", { exact: true }).fill("17");
  await page.getByRole("switch", { name: /Reduction sur le paiement en ligne/ }).check();
  await page.getByRole("button", { name: "Enregistrer", exact: true }).click();
  await expect.poll(async () => (await db.settings.findUniqueOrThrow({ where: { id: 1 } })).discountPercent).toBe(17);
  await page.getByRole("link", { name: "Contenus du site" }).click();
  await page.getByLabel("Accueil : sous-titre", { exact: true }).fill(`Brouillon ${marker}`);
  await page.getByRole("button", { name: "Enregistrer le brouillon" }).click();
  await expect(page.getByText("Brouillon en attente", { exact: true })).toBeVisible();
  const publicPage = await context.newPage();
  await publicPage.goto(origin);
  await expect(publicPage.locator(".hero-subtitle")).not.toHaveText(`Brouillon ${marker}`);
  await publicPage.goto(`${origin}/?preview=1`);
  await expect(publicPage.locator(".hero-subtitle")).toHaveText(`Brouillon ${marker}`);
  await publicPage.close();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${origin}/dashboard?view=overview`, { waitUntil: "networkidle" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(artifacts, "mobile-dashboard.png") });
  const unauthorized = await browser.newContext();
  expect((await unauthorized.request.get(`${origin}/api/admin`)).status()).toBe(401);
  expect((await context.request.post(`${origin}/api/admin`, { headers: { origin: "https://invalid.test" }, data: { resource: "settings", data: {} } })).status()).toBe(403);
  const editorEmail = `editor-${marker}@example.test`;
  const editor = await db.staff.create({ data: { name: `UI Editor ${marker}`, email: editorEmail, job: "Test temporaire", role: "EDITOR", passwordHash: await hash(password, 12) } });
  editorId = editor.id;
  expect((await unauthorized.request.post(`${origin}/api/auth`, { headers: { origin }, data: { email: editorEmail, password } })).status()).toBe(200);
  expect((await unauthorized.request.post(`${origin}/api/admin`, { headers: { origin }, data: { resource: "settings", data: {} } })).status()).toBe(403);
  const editorData = await (await unauthorized.request.get(`${origin}/api/admin`)).json();
  expect(editorData.reservations).toEqual([]);
  expect(editorData.members).toEqual([]);
  await unauthorized.close();
  expect(errors).toEqual([]);
  console.log("PASS: desktop/mobile, gallery, menu, reservation, auth, provisional status, MySQL settings, drafts, media upload, editor permissions and CSRF.");
  console.log(`Screenshots: ${artifacts}`);
} finally {
  const reservations = await db.reservation.findMany({ where: { name: customer }, select: { id: true } });
  await db.audit.deleteMany({ where: { OR: [{ reservationId: { in: reservations.map(reservation => reservation.id) } }, { actor: { in: [`UI Admin ${marker}`, `UI Editor ${marker}`] } }] } });
  await db.reservation.deleteMany({ where: { name: customer } });
  await db.rateLimit.deleteMany({ where: { key: createHash("sha256").update(`booking:${phone.replace(/\D/g, "")}`).digest("hex") } });
  if (accountId) await db.staff.delete({ where: { id: accountId } });
  if (editorId) await db.staff.delete({ where: { id: editorId } });
  if (uploadedMediaId) await db.media.delete({ where: { id: uploadedMediaId } });
  if (uploadedFileName) await unlink(fileURLToPath(new URL(`../storage/uploads/${uploadedFileName}`, import.meta.url))).catch(() => {});
  const { Prisma } = await import("@prisma/client");
  await db.settings.update({ where: { id: 1 }, data: { discountPercent: originalSettings.discountPercent, discountEnabled: originalSettings.discountEnabled, draftContent: originalSettings.draftContent ?? Prisma.DbNull } });
  await context.close(); await browser.close(); await db.$disconnect();
}
}

main().catch(error => { console.error(error); process.exitCode = 1; });